name: dart_syslog
description: A syslog protocol (RFC 3164/RFC 5424) implementation that only supports UDP transport.
version: 0.1.0
repository: https://github.com/espresso3389/dart_syslog

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  intl: ^0.18.1
  synchronized: ^3.1.0
  udp: ^5.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
